const express = require('express')
const app = express()
const path =require('path')
app.use(express.static(__dirname + "/dist/reduximplementation"))
app.get('*',function (req,res) {
  res.sendFile(path.join(__dirname+'/dist/reduximplementation/index.html'))
})
app.listen(process.env.PORT || 4200)
const jsonServer = require('json-server')
const server = jsonServer.create()
const router = jsonServer.router('db.json')
const middlewares = jsonServer.defaults()
server.use(middlewares)
server.use(router)
server.listen(3000, () => {
  console.log('JSON Server is running')
})
